require('dotenv').config();
const mongoose = require('mongoose');
// Import the model

// Place the array you want to seed
const mainBlock = [
  {
    "universe":"DC",
    "name": "Part 1",
    "order":"1",
    "partOf":"",    
    "years": "1938-1986",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Jack Kirby's Fourth World","Aquaman: Death of a Prince", "Crisis on Infinite Earths" ],
    "issues": "",
    "description": "The first part of the order contains all the Pre-Crisis comics and ends with the Crisis on Infinite Earths event.  The beginning of the order starts off heavily with the Superman Family but gradually other characters are brought in.  A lot of the Golden and Silver age comics rely on extreme amounts of coincidence for their plots,  which doesn’t always make for the easiest reading.  If you are mainly interested in the Post-Crisis DC Universe you should skip this part and begin reading at Part 2.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 2",
    "order":"2", 
    "partOf":"",   
    "years": "1987-1990",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Legends", "Millennium", "Invasion!", "Superman: Exile", "Janus Directive", "Batman: A Lonely Place of Dying", "War of the Gods"],
    "issues": "",
    "description": "The beginning of the Post-Crisis era.  We start off with a high concentration of some of the most iconic Batman stories of all time;  Year One,  The Long Halloween,  Dark Victory,  Killing Joke,  and A Lonely Place of Dying.   Also featured is the excellent Man of Steel limited series and the Post-Crisis origins of many of the biggest DC superheroes.  Post-Crisis we also see the beginning of large crossover events.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 3",
    "order":"3",
    "partOf":"",    
    "years": "1991-1997",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Panic in the Sky", "Justice League: Breakdowns", "Armageddon 2001", "Eclipso: The Darkness Within", "Death of Superman", "Funeral for a Friend", "Reign of the Supermen", "Bloodlines", "DC Universe: Trinity", "Knightfall Saga", "Batman: Prodigal", "Batman: Troika", "Zero Hour", "The Trial of Superman", "Underworld Unleashed", "The Flash: Dead Heat", "Batman: Contagion", "Batman: Legacy", "Final Night"],
    "issues": "",
    "description": "Along with the annual crossover events we also see two of the biggest comic events of the 90's;  Death of Superman and the Knightfall Saga.  These two events helped fuel the speculator boom of the early 90's and ultimately played a significant part in the collapse of the comic book market.  The Batman: Contagion event marks the beginning of a series of events that will culminate in Batman: No Man's Land several years later.  Zero Hour is the second of DC's large “Crisis” events.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 4",
    "order":"4",
    "partOf":"",    
    "years": "1997-2002",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Genesis", "Batman: Cataclysm", "Brotherhood of the Fist", "Behold! The Millennium Giants", "DC One Million", "Batman: No Man's Land", "Day of Judgment", "The Justice Society Returns!", "Superman: Emperor Joker", "Batman: Officer Down", "Our Worlds at War", "Joker's Last Laugh"],
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 5",
    "order":"5",
    "partOf":"",    
    "years": "2000-2005",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Bruce Wayne: Murderer?", "Bruce Wayne: Fugitive", "World Without Young Justice", "JSA: Black Reign", "Batman: War Games"],
    "issues": "",
    "description": "The popular Batman storyline Hush takes place in this part of the order and we have an updated version of Superman's Post-Crisis origin with the the Superman: Birthright limited series.  The Dark Knight Returns and The Dark Knight Strikes Again are placed in this section since they have to appear somewhere.  We also have the excellent alternate universe Superman: Red Son limited series.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 6",
    "order":"6", 
    "partOf":"",   
    "years": "2005-2009",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Identity Crisis", "Countdown to Infinite Crisis", "Batman: War Crimes", "Infinite Crisis", "Batman: Face the Face", "Superman: Up, Up, and Away!", "Amazons Attack!", "Lightning Saga", "The Resurrection of Ra's al Ghul", "Sinestro Corps War"],
    "issues": "",
    "description": "And here we go.  First up is Identity Crisis,  followed by the massive Countdown to Infinite Crisis and then the Infinite Crisis event itself.  This is followed by the 52 limited series and the One Year Later storylines,  which explore the changes in the status quo of various heroes after the Infinite Crisis event.  During the Countdown to Infinite Crisis we have the excellent Green Lantern: Rebirth limited series and the beginning of Geoff Johns epic run with the character.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 7",
    "order":"7",
    "partOf":"",   
    "years": "2008-2011",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Final Crisis", "Battle for the Cowl", "Blackest Night", "Brightest Day", "Superman: New Krypton", "Batman: Judgment on Gotham", "Reign of Doomsday", "War of the Green Lanterns", "Flashpoint"],
    "issues": "",
    "description": "We have yet another “Crisis” event with Final Crisis,  which has major repercussions within the Batman Family series of comics.  There are several huge events such as Blackest Night,  Brightest Day,  and Superman: New Krypton.  Then there is Flashpoint which radically changes the DC Universe and ushers in the New 52 era.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "New 52",
    "order":"8",
    "partOf":"",   
    "years": "2011-2015",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Batman: Zero Year", "The Culling", "Night of the Owls", "Rise of the Third Army", "Wrath of the First Lantern", "Rotworld", "Throne of Atlantis", "Superman: H'el on Earth", "Death of the Family", "Green Lantern: Lights Out", "Batman: Requiem", "Gothtopia", "Trinity War", "Forever Evil", "Forever Evil: Blight", "Krypton Returns", "Red Daughter of Krypton", "Superman: Doomed", "Robin Rises", "Green Lantern: Uprising", "New 52: Futures End", "Green Lantern: Godhead", "Batman: Endgame", "Multiversity", "Convergence"],
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "DC You",
    "order":"9", 
    "partOf":"",   
    "years": "2015-2016",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Superman: Savage Dawn", "Robin War", "Darkseid War", "Final Days of Superman"],
    "issues": "",
    "description": "Welcome to the DC You Reading Order.  Following the Convergence event the New 52 branding was dropped from all DC comics and was replaced by the DC You branding.  DC You begins after the Convergence event and ends with DC Rebirth.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "DC Rebirth",
    "order":"10",
    "partOf":"",    
    "years": "2016-2021",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Night of the Monster Men",  "Justice League vs. Suicide Squad", "Superman Reborn", "The Lazarus Contract", "Dark Nights: Metal", "Heroes in Crisis", "Drowned Earth", "Event Leviathan", "City of Bane", "The Infected", "Joker War", "Dark Nights: Death Metal", "Endless Winter", "Future State"],
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Part 8",
    "order":"11",
    "partOf":"",    
    "years": "2010-2021+",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Injustice,  DCeased"],
    "issues": "",
    "description": "The New 52, DC You, and DC Rebirth reading orders only contain in-continuity comic issues. This part of the reading order is dedicated to the non-canon comics DC has released since 2011. Non-canon comics in the Infinite Frontier era will also be added to this reading order.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Infinite Frontier",
    "order":"11", 
    "partOf":"",   
    "years": "2010-2021+",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "part",    
    "events": ["Fear State", "Trial of the Amazons", "Shadow War", "Dark Crisis"],
    "issues": "",
    "description": "Infinite Frontier is the name of the new era of DC Comics, following DC Rebirth. Rather than serve as a line-wide reboot, Infinite Frontier keeps the previous stories canon, while making many of the pre-Flashpoint storylines canon too. It also focuses on new or reintroduced characters, while allowing writers more creative freedom in telling their stories.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Jack Kirby's Fourth World",
    "order":"1",
    "partOf":"Part 1",    
    "years": "1970",     
    "previousEvent": "Zatanna's Search",
    "nextEvent": "Aquaman: Death of a Prince",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856461/House%20of%20Heroes/DC/Part%201/Jack_Kirby_s_Fourth_World_wd2fpn.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues":"",
    "description": "The Fourth World is a science-fiction based mythology revolving around ancient space deities known as the New Gods. Similar to the gods of Earth lore, the New Gods are larger than life, possessing fantastic powers, which they use in a never-ending struggle between good and evil.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Aquaman: Death of a Prince",
    "order":"2",
    "partOf":"Part 1",    
    "years": "1974",     
    "previousEvent": "Jack Kirby's Fourth World",
    "nextEvent": "Crisis on Infinite Earths",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856461/House%20of%20Heroes/DC/Part%201/Aquaman_Death_of_a_Prince_tz19hr.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "As Aquaman faces his greatest foes, Black Manta plans his ultimate revenge on the Sea King, resulting in the death of Aquaman's infant son and the dissolution of his marriage.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Crisis on Infinite Earths",
    "order":"3",
    "partOf":"Part 1",    
    "years": "1985",     
    "previousEvent": "Aquaman: Death of a Prince",
    "nextEvent": "Legends",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856461/House%20of%20Heroes/DC/Part%201/Crisis_on_Infinite_Earths_kwnrdl.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "The Crisis on Infinite Earths was a Multiversal catastrophe that resulted in the destruction of countless parallel universes,  and the recreation of a single universe.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Legends",
    "order":"1",
    "partOf":"Part 2",    
    "years": "1986",     
    "previousEvent": "Crisis on Infinite Earths",
    "nextEvent": "Millennium",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856490/House%20of%20Heroes/DC/Part%202/Legends_ekfb11.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Darkseid wants to destabilize Earth's power structure so he can harvest the Anti-Life Equation.  He decides that humanity will be easier to control if he destroys the legends that inspire them.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Millennium",
    "order":"2",
    "partOf":"Part 2",    
    "years": "1987",     
    "previousEvent": "Legends",
    "nextEvent": "Invasion!",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856490/House%20of%20Heroes/DC/Part%202/Millennium_ajijnz.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Aliens visit Earth to start the next wave of human evolution.  Ten humans are chosen to advance and become immortals,  given special powers.  They are attacked by Manhunter agents,  part of an alien conspiracy posing as close friends and relatives to every single superhero.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Invasion!",
    "order":"3",
    "partOf":"Part 2",    
    "years": "1989",     
    "previousEvent": "Millennium",
    "nextEvent": "Superman: Exile",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856489/House%20of%20Heroes/DC/Part%202/Invasion_kbj903.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "The Alien Alliance,  led by the war-like Dominators and Khunds,  intend on wiping out humanity to destroy all of Earth's metahumans.  This all-out assault on superheroes leads to a war consuming the entire world,  and ramifications throughout the universe.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Superman: Exile",
    "order":"4",
    "partOf":"Part 2",    
    "years": "1989",     
    "previousEvent": "Invasion!",
    "nextEvent": "Janus Directive",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856490/House%20of%20Heroes/DC/Part%202/Superman_Exile_gif270.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Guilt drives Superman into space,  where he hopes to forge a new life for himself away from Earth,  and thus never be forced to hurt anyone again.  During his space travels Superman discovers both new and old foes,  and reconsiders his choices.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Janus Directive",
    "order":"5",
    "partOf":"Part 2",    
    "years": "1989",     
    "previousEvent": "Superman: Exile",
    "nextEvent": "Batman: A Lonely Place of Dying",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856489/House%20of%20Heroes/DC/Part%202/Janus_Directive_vmennp.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Various metahuman military agencies in the U.S. receive intel called the “Janus Directive.”   It details how each of the other agencies are plotting against them.  Someone is manipulating the various agencies in order to distract them.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Batman: A Lonely Place of Dying",
    "order":"6",
    "partOf":"Part 2",    
    "years": "1989",     
    "previousEvent": "Janus Directive",
    "nextEvent": "War of the Gods",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856489/House%20of%20Heroes/DC/Part%202/Batman_A_Lonely_Place_of_Dying_rdiwaf.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Traumatized by the death of Jason Todd, Batman begins a brutal quest for retribution. Deducing the connection between Bruce Wayne and Batman as well as the repercussions that the murder are having on him, Tim Drake seeks out Dick Grayson in a desperate attempt to reunite the Dynamic Duo.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "War of the Gods",
    "order":"7",
    "partOf":"Part 2",    
    "years": "1991",     
    "previousEvent": "Batman: A Lonely Place of Dying",
    "nextEvent": "Panic in the Sky",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856489/House%20of%20Heroes/DC/Part%202/War_of_the_Gods_qk6ovv.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Ancient gods suddenly begin trying to destroy the Earth and each other.  While the ancient Roman gods wage war with the Olympian gods,  the Egyptian,  African,  Norse,  Babylonian,  and Thanagarian gods each want to recreate the world in their own images,  and attack the superheroes who stand in their way.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Panic in the Sky",
    "order":"1",
    "partOf":"Part 3",    
    "years": "1992",     
    "previousEvent": "War of the Gods",
    "nextEvent": "Justice League: Breakdowns",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Brainiac seizes control of Warworld.  He then brainwashes Supergirl and the alien warrior Draaga before capturing Metron and setting off for Earth.  Superman gathers a coalition of superheroes and launches a preemptive strike at Warworld before it can arrive on Earth.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Justice League: Breakdowns",
    "order":"2",
    "partOf":"Part 3",    
    "years": "1991",     
    "previousEvent": "Panic in the Sky",
    "nextEvent": "Armageddon 2001",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856502/House%20of%20Heroes/DC/Part%203/Justice-League_Breakdowns_xenlpn.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "A series of events hammer the Justice League,  from assassinations to coup attempts.  Will the Justice League be able to handle it?",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Armageddon 2001",
    "order":"3",
    "partOf":"Part 3",    
    "years": "1991",     
    "previousEvent": "Justice League: Breakdowns",
    "nextEvent": "Eclipso: The Darkness Within",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856501/House%20of%20Heroes/DC/Part%203/Armageddon_2001_oe1arj.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Armageddon 2001 refers to a gigantic battle between all of Earth’s heroes and a villain known only as Monarch, in which the superheroes were slain and the all-powerful Monarch plunged the world into a totalitarian government underneath his rule.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Eclipso: The Darkness Within",
    "order":"4",
    "partOf":"Part 3",    
    "years": "1992",     
    "previousEvent": "Armageddon 2001",
    "nextEvent": "Death of Superman",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856502/House%20of%20Heroes/DC/Part%203/Eclipso_The_Darkness_Within_gkqhpp.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "From his palace on Earth's moon Eclipso uses hate as a trigger to possess other beings. Whenever someone who has a black diamond in their possession gets angry, Eclipso can instantly take control of that particular person.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Death of Superman",
    "order":"5",
    "partOf":"Part 3",    
    "years": "1992",     
    "previousEvent": "Eclipso: The Darkness Within",
    "nextEvent": "Funeral for a Friend",
    "image": "https://res.cloudinary.com/dtxouyldc/image/upload/v1661856502/House%20of%20Heroes/DC/Part%203/Death_of_Superman_bcfrbh.jpg",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "Doomsday is here.   Superman engages in battle with a seemingly unstoppable killing machine named Doomsday in the streets of Metropolis.",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "Funeral for a Friend",
    "order":"6",
    "partOf":"Part 3",    
    "years": "1993",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },
  {
    "universe":"DC",
    "name": "",
    "order":"",
    "partOf":"Part 3",    
    "years": "",     
    "previousEvent": "",
    "nextEvent": "",
    "image": "",
    "complementaryImages": "",
    "type": "event",    
    "events": "",
    "issues": "",
    "description": "",
    "summary": "",      
  },

  



  ]

mongoose.connect(process.env.MONGO_URL)
  .then(x => console.log(`Connected to ${x.connection.name}`))
  .then(() => {
    return // Model.create(array)
  })
  .then(() => {
    console.log('Seed done 🌱');
  })
  .catch(e => console.log(e))
  .finally(() => {
    console.log('Closing connection');
    mongoose.connection.close();
  })

// Run npm run seed 