const parts = [
    {
      "universe":"DC",
      "name": "Part 1",
      "order":"1",           
      "years": "1938-1986",            
      "events": ["Jack Kirby's Fourth World","Aquaman: Death of a Prince", "Crisis on Infinite Earths" ],
      "issues": "",
      "description": "The first part of the order contains all the Pre-Crisis comics and ends with the Crisis on Infinite Earths event.  The beginning of the order starts off heavily with the Superman Family but gradually other characters are brought in.  A lot of the Golden and Silver age comics rely on extreme amounts of coincidence for their plots,  which doesn’t always make for the easiest reading.  If you are mainly interested in the Post-Crisis DC Universe you should skip this part and begin reading at Part 2.",             
    },
    {
      "universe":"DC",
      "name": "Part 2",
      "order":"2",          
      "years": "1987-1990",            
      "events": ["Legends", "Millennium", "Invasion!", "Superman: Exile", "Janus Directive", "Batman: A Lonely Place of Dying", "War of the Gods"],
      "issues": "",
      "description": "The beginning of the Post-Crisis era.  We start off with a high concentration of some of the most iconic Batman stories of all time;  Year One,  The Long Halloween,  Dark Victory,  Killing Joke,  and A Lonely Place of Dying.   Also featured is the excellent Man of Steel limited series and the Post-Crisis origins of many of the biggest DC superheroes.  Post-Crisis we also see the beginning of large crossover events.",           
    },
    {
      "universe":"DC",
      "name": "Part 3",
      "order":"3",           
      "years": "1991-1997",            
      "events": ["Panic in the Sky", "Justice League: Breakdowns", "Armageddon 2001", "Eclipso: The Darkness Within", "Death of Superman", "Funeral for a Friend", "Reign of the Supermen", "Bloodlines", "DC Universe: Trinity", "Knightfall Saga", "Batman: Prodigal", "Batman: Troika", "Zero Hour", "The Trial of Superman", "Underworld Unleashed", "The Flash: Dead Heat", "Batman: Contagion", "Batman: Legacy", "Final Night"],
      "issues": "",
      "description": "Along with the annual crossover events we also see two of the biggest comic events of the 90's;  Death of Superman and the Knightfall Saga.  These two events helped fuel the speculator boom of the early 90's and ultimately played a significant part in the collapse of the comic book market.  The Batman: Contagion event marks the beginning of a series of events that will culminate in Batman: No Man's Land several years later.  Zero Hour is the second of DC's large “Crisis” events.",
    },
    {
      "universe":"DC",
      "name": "Part 4",
      "order":"4",           
      "years": "1997-2002",            
      "events": ["Genesis", "Batman: Cataclysm", "Brotherhood of the Fist", "Behold! The Millennium Giants", "DC One Million", "Batman: No Man's Land", "Day of Judgment", "The Justice Society Returns!", "Superman: Emperor Joker", "Batman: Officer Down", "Our Worlds at War", "Joker's Last Laugh"],
      "issues": "",
      "description": "This part of the reading order starts off with a revamped Justice League being written by Grant Morrison and also sees the return of the Justice Society.  The DC One Million event depicts the DC Universe 83,000 years in the future.  Gotham City continues to have a bad time in Batman: Cataclysm and the government finally says enough is enough in Batman: No Man's Land.",
    },
    {
      "universe":"DC",
      "name": "Part 5",
      "order":"5",           
      "years": "2000-2005",           
      "events": ["Bruce Wayne: Murderer?", "Bruce Wayne: Fugitive", "World Without Young Justice", "JSA: Black Reign", "Batman: War Games"],
      "issues": "",
      "description": "The popular Batman storyline Hush takes place in this part of the order and we have an updated version of Superman's Post-Crisis origin with the the Superman: Birthright limited series.  The Dark Knight Returns and The Dark Knight Strikes Again are placed in this section since they have to appear somewhere.  We also have the excellent alternate universe Superman: Red Son limited series.",
    },
    {
      "universe":"DC",
      "name": "Part 6",
      "order":"6",          
      "years": "2005-2009",            
      "events": ["Identity Crisis", "Countdown to Infinite Crisis", "Batman: War Crimes", "Infinite Crisis", "Batman: Face the Face", "Superman: Up, Up, and Away!", "Amazons Attack!", "Lightning Saga", "The Resurrection of Ra's al Ghul", "Sinestro Corps War"],
      "issues": "",
      "description": "And here we go.  First up is Identity Crisis,  followed by the massive Countdown to Infinite Crisis and then the Infinite Crisis event itself.  This is followed by the 52 limited series and the One Year Later storylines,  which explore the changes in the status quo of various heroes after the Infinite Crisis event.  During the Countdown to Infinite Crisis we have the excellent Green Lantern: Rebirth limited series and the beginning of Geoff Johns epic run with the character.",
    },
    {
      "universe":"DC",
      "name": "Part 7",
      "order":"7",          
      "years": "2008-2011",            
      "events": ["Final Crisis", "Battle for the Cowl", "Blackest Night", "Brightest Day", "Superman: New Krypton", "Batman: Judgment on Gotham", "Reign of Doomsday", "War of the Green Lanterns", "Flashpoint"],
      "issues": "",
      "description": "We have yet another “Crisis” event with Final Crisis,  which has major repercussions within the Batman Family series of comics.  There are several huge events such as Blackest Night,  Brightest Day,  and Superman: New Krypton.  Then there is Flashpoint which radically changes the DC Universe and ushers in the New 52 era.",
    },
    {
      "universe":"DC",
      "name": "New 52",
      "order":"8",          
      "years": "2011-2015",            
      "events": ["Batman: Zero Year", "The Culling", "Night of the Owls", "Rise of the Third Army", "Wrath of the First Lantern", "Rotworld", "Throne of Atlantis", "Superman: H'el on Earth", "Death of the Family", "Green Lantern: Lights Out", "Batman: Requiem", "Gothtopia", "Trinity War", "Forever Evil", "Forever Evil: Blight", "Krypton Returns", "Red Daughter of Krypton", "Superman: Doomed", "Robin Rises", "Green Lantern: Uprising", "New 52: Futures End", "Green Lantern: Godhead", "Batman: Endgame", "Multiversity", "Convergence"],
      "issues": "",
      "description": "",
    },
    {
      "universe":"DC",
      "name": "DC You",
      "order":"9",         
      "years": "2015-2016",            
      "events": ["Superman: Savage Dawn", "Robin War", "Darkseid War", "Final Days of Superman"],
      "issues": "",
      "description": "Welcome to the DC You Reading Order.  Following the Convergence event the New 52 branding was dropped from all DC comics and was replaced by the DC You branding.  DC You begins after the Convergence event and ends with DC Rebirth.",
    },
    {
      "universe":"DC",
      "name": "DC Rebirth",
      "order":"10",           
      "years": "2016-2021",            
      "events": ["Night of the Monster Men",  "Justice League vs. Suicide Squad", "Superman Reborn", "The Lazarus Contract", "Dark Nights: Metal", "Heroes in Crisis", "Drowned Earth", "Event Leviathan", "City of Bane", "The Infected", "Joker War", "Dark Nights: Death Metal", "Endless Winter", "Future State"],
      "issues": "",
      "description": "",
    },
    {
      "universe":"DC",
      "name": "Part 8",
      "order":"11",           
      "years": "2010-2021+",            
      "events": ["Injustice,  DCeased"],
      "issues": "",
      "description": "The New 52, DC You, and DC Rebirth reading orders only contain in-continuity comic issues. This part of the reading order is dedicated to the non-canon comics DC has released since 2011. Non-canon comics in the Infinite Frontier era will also be added to this reading order.",
    },
    {
      "universe":"DC",
      "name": "Infinite Frontier",
      "order":"11",         
      "years": "2010-2021+",            
      "events": ["Fear State", "Trial of the Amazons", "Shadow War", "Dark Crisis"],
      "issues": "",
      "description": "Infinite Frontier is the name of the new era of DC Comics, following DC Rebirth. Rather than serve as a line-wide reboot, Infinite Frontier keeps the previous stories canon, while making many of the pre-Flashpoint storylines canon too. It also focuses on new or reintroduced characters, while allowing writers more creative freedom in telling their stories.",
              
    },
    {
      "universe":"MARVEL",
      "name": "Part 1",
      "order":"1",              
      "years": "1961-1972", 
      "events": "",
      "issues": "",
      "description": "Containing by far the most first appearances of significant characters of any Marvel era.  You will see how the biggest superheroes in the Marvel Universe received their superpowers and witness the foundation that decades of comics will be built on.  Witness the formation of the X-Men,  Fantastic Four,  and Avengers.  Like most Silver Age comics there are numerous guest appearances but few actual crossovers.  The beginning of the reading order features numerous limited series that take place chronologically before,  as well as during,  the earliest published Marvel comics.",
    },
    {
      "universe":"MARVEL",
      "name": "Part 2",
      "order":"2",              
      "years": "1972-1981",    
      "events": ["Avengers/Defenders War", "Thanos War"],
      "issues": "",
      "description": "Containing the second most first appearances of significant characters,  we see the introduction of some extremely popular heroes,  especially among the X-Men.  We also see the first significant crossover when the Avengers battle the Defenders.  This part of the reading order also contains some of the most popular X-Men storylines of all time;  the Phoenix Saga,  Dark Phoenix Saga,  and Days of Future Past.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 3",
        "order":"3",              
        "years": "1972-1981",    
        "events": ["Wraith War", "Secret Wars II", "Mutant Massacre"],
        "issues": "",
        "description": "Here we see the birth of large scale crossover events.  Contest of Champions is Marvel's first Limited Series and serves as a sort of prototype for the line-wide crossovers to follow.  The original Secret Wars event is wildly successful and its less successful sequel comes out a year later.  The X-Men line expands with the introduction of X-Factor and the New Mutants.  The popular villain Apocalypse is introduced and we see the beginnings of the symbiote that will go one to become Venom.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 4",
        "order":"4",              
        "years": "1986-1993",     
        "events": ["Kraven's Last Hunt", "Fall of the Mutants", "Evolutionary War", "Inferno", "Atlantis Attacks", "Acts of Vengeance", "Days of Future Present", "X-Tinction Agenda", "Muir Island Saga", "Infinity Gauntlet", "Operation: Galactic Storm", "Infinity War", "Dead Man's Hand", "Rise of the Midnight Sons", "X-Cutioner's Song"],
        "issues": "",
        "description": "Now we really see the crossover events swing into high gear.  The Infinity Gauntlet event takes place,  one of the greatest comic events ever.  Venom,  Gambit,  and the mutant group X-Force are introduced and prove to be immensely popular.  In the comic book business the speculator market is in full swing but its end is already in sight.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 5",
        "order":"5",              
        "years": "1992-1999",    
        "events": ["For Love Nor Money", "Maximum Carnage", "Infinity Crusade", "Blood and Thunder", "Fatal Attractions", "Bloodties", "Marvel 2099", "Midnight Massacre", "Road to Vengeance: Missing Link", "Siege of Darkness", "Child's Play", "Time and Time Again", "Phalanx Covenant", "Countdown", "Age of Apocalypse", "Second Clone Saga", "Over the Edge", "Onslaught Saga", "Operation: Zero Tolerance", "Heroes Reborn", "Spider-Man: Identity Crisis", "MC2", "Eighth Day", "The Hunt for Xavier", "Magneto War"],
        "issues": "",
        "description": "The 90's “Dark Age of Comics” is in full swing.  If you are a fan of pouches you are in luck.  We see the seminal X-Men event Age of Apocalypse as well as the will-it-ever-end Spider-Man event Second Clone Saga.  The first of several Marvel Alternate Universes are printed in this era;  the futuristic Marvel 2099 and the MC2 universe,  which mainly featured Spider-Girl.  Near the end of this section we see many of the most popular and long-running Marvel series relaunched with new #1 issues that will serve as a good jumping on point for new readers.  In the comic business world the market crashes and the industry is devastated.",               
    },
    {
        "universe":"MARVEL",
        "name": "Part 6",
        "order":"6",              
        "years": "1999-2004",    
        "events": ["Apocalypse: The Twelve", "Maximum Security", "Eve of Destruction", "Earth X"],
        "issues": "",
        "description": "Here we see the start of Grant Morrison's work on the X-Men with New X-Men #114 which can be seen as the start of the “Modern Age of Marvel” and serves as an excellent point to begin reading Marvel comics as it forms the basis for the X-Men moving forward and the beginning of the modern mega events is just around the corner.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 7",
        "order":"7",              
        "years": "2002-2007",    
        "events": ["Marvel 1602", "Avengers Disassembled", "House of M", "Decimation", "Spider-Man: The Other"],
        "issues": "",
        "description": "The era of Marvel mega events starts here with the Avengers Disassembled event and the beginning of the New Avengers series.  Following that we have House of M which will have repercussions through the various X-Men books for years to come.  Garth Ennis' fantastic run on Punisher continues with Punisher Vol. 6 under the MAX imprint.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 8",
        "order":"8",              
        "years": "2005-2009",   
        "events": ["Civil War", "One More Day", "Planet Hulk", "The Initiative", "World War Hulk", "Annihilation,  X-Men: Endangered Species", "X-Men: Messiah Complex", "X-Men: Divided We Stand", "X-Men: Manifest Destiny", "X-Men: Original Sin", "Messiah War", "Annihilation: Conquest", "Secret Invasion"],
        "issues": "",
        "description": "Start off with Civil War,  one of the biggest Marvel events ever,  and follow that with the excellent Planet Hulk and Annihilation events,  a string of X-Men events,  the Wolverine storyline Old Man Logan,  and then finish it all off with the massive Secret Invasion event and you have a packed reading order.  Unfortunately One More Day also takes place during this time.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 9",
        "order":"9",              
        "years": "2009-2011",     
        "events": "",
        "issues": "",
        "description": "The tightly packed events continue.  The cosmic saga of Marvel,  which is one of the highlights of recent Marvel history,  continues with War of Kings,  Realm of Kings,  and The Thanos Imperative.  The status quo after Secret Invasion is explored in the 300!? issue Dark Reign era.  Siege marks the culmination of events that started with Avengers Disassembled.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 10",
        "order":"10",              
        "years": "2011-2012",     
        "events": "",
        "issues": "",
        "description": "The X-Men split apart and then battle the Avengers.  In 2012 Marvel NOW! starts and provides an excellent starting point for readers new to Marvel comics.  Years of storylines culminate in the Secret Wars (2015) event which makes way for an All-New All-Different Marvel.",
    },
    {
        "universe":"MARVEL",
        "name": "Marvel NOW!",
        "order":"11",              
        "years": "2012-2016",     
        "events": ["Age of Ultron", "Infinity", "Inhumanity", "Battle of the Atom", "The Trial of Jean Grey", "Goblin Nation", "Original Sin", "Death of Wolverine", "Avengers & X-Men: AXIS", "Spider-Verse", "The Black Vortex", "Secret Wars (2015)"],
        "issues": "",
        "description": "Welcome to the Marvel NOW! Reading Order.  Marvel NOW! presents a shift in the Marvel Universe following the Avengers vs. X-Men event and was designed as a jumping on point for new readers and featured many changes to character status quos,  alter egos,  and costumes.  Marvel NOW! ended with the conclusion of the Secret Wars (2015) event and made way for All-New All-Different Marvel.",
    },
    {
        "universe":"MARVEL",
        "name": "All-New, All-Different Marvel",
        "order":"12",             
        "years": "2015-2018",     
        "events": ["Avengers: Standoff!", "Spider-Women", "Apocalypse Wars", "Civil War II", "Dead No More: The Clone Conspiracy", "Monsters Unleashed", "Inhumans vs. X-Men", "Secret Empire"],
        "issues": "",
        "description": "Coming after the Secret Wars (2015) event is an All-New, All-Different Marvel;  meant to reveal the state of the post-Secret Wars Marvel Universe and provide a jumping on point for new readers.  Even though after the Civil War II event Marvel began to reuse the Marvel NOW! banner on comic books,  for simplicity's sake this reading order considers everything post-Secret Wars (2015) to the beginning of Marvel Legacy to be All-New, All-Different Marvel.",
    },
    {
        "universe":"MARVEL",
        "name": "Marvel Legacy",
        "order":"13",              
        "years": "2017-2018",     
        "events": ["Venomverse", "Venom Inc.", "Damnation", "Infinity Countdown"],
        "issues": "",
        "description": "A relaunch following the Secret Empire event, Marvel Legacy attempted to bring a greater focus to Marvel's core superheroes. It saw the return of Bruce Banner as Hulk, Tony Stark as Iron Man, and Thor Odinson reclaiming the hammer Mjolnir. Wolverine, Jean Grey, and Franklin and Valeria Richards are all back; while the Thing and Human Torch search for Sue and Reed Richards, who have been missing since Secret Wars.",
    },
    {
        "universe":"MARVEL",
        "name": "A Fresh Start",
        "order":"14",              
        "years": "2018-2019",     
        "events": ["Infinity Wars", "Spider-Geddon", "Age of X-Man", "War of the Realms", "Absolute Carnage"],
        "issues": "",
        "description": "A Fresh Start saw the return of Tony Stark, Steve Rogers, Logan, Odinson and Bruce Banner to their classic identities of Iron Man, Captain America, Wolverine, Thor and Hulk respectively. The War of the Realms event caps off a seven year run of Thor stories by Jason Aaron. Also Marvel decides to go overboard with all the limited series and one-shots.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 11",
        "order":"15",              
        "years": "2019-2021",    
        "events": ["Annihilation: Scourge", "2099", "Iron Man 2020", "Empyre", "X of Swords", "King In Black"],
        "issues": "",
        "description": "Continuing from A Fresh Start the Marvel Universe rolls on. A new era for the X-Men begins, overseen by Jonathan Hickman.",
    },
    {
        "universe":"MARVEL",
        "name": "Part 12",
        "order":"16",              
        "years": "2020-2022",     
        "events": ["Heroes Reborn (2021)", "Hellfire Gala", "Death of Doctor Strange", "Devil's Reign"],
        "issues": "",
        "description": "",
    },
]